plugins:
  - jest
  - prettier
env:
  node: true
  es2021: true
extends:
  - airbnb-base
  - plugin:jest/recommended
  - prettier
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: { import/no-extraneous-dependencies: [0, { devDependencies: true }], prettier/prettier: 'error' }
